/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TodoAppFrame.java
 *
 * Created on Oct 13, 2008, 9:47:13 PM
 */

package org.jtodo.ui;

import javax.swing.UIManager;

/**
 *
 * @author XR1CTSO
 */
public class TodoAppFrame extends javax.swing.JFrame {

    /** Creates new form TodoAppFrame */
    public TodoAppFrame() {
        initComponents();
        setSize(664,370);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashBoardUIPanel1 = new org.jtodo.ui.DashBoardUIPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(dashBoardUIPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws Exception {
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodoAppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jtodo.ui.DashBoardUIPanel dashBoardUIPanel1;
    // End of variables declaration//GEN-END:variables

}
