/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DashBoardUIPanel.java
 *
 * Created on Oct 14, 2008, 3:14:42 PM
 */
package org.jchronos.ui;

import com.jhlabs.image.BlurFilter;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import org.jdesktop.jxlayer.JXLayer;
import org.jdesktop.jxlayer.plaf.ext.LockableUI;
import org.jdesktop.jxlayer.plaf.effect.BufferedImageOpEffect;
import org.jdesktop.jxlayer.plaf.effect.LayerEffect;
import org.jchronos.ui.ext.VerticalLabelUI;

/**
 *
 * @author XR1CTSO
 */
public class DashBoardUIPanel extends javax.swing.JPanel {

    private JXLayer<JComponent> jXLayer = null;
    TodoLockableUI lockableUI = new TodoLockableUI(new BufferedImageOpEffect(new BlurFilter()));

    /** Creates new form DashBoardUIPanel */
    public DashBoardUIPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainUIPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        quadrantPanel1 = new org.jchronos.ui.QuadrantPanel();
        xLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        yLabel.setUI(new VerticalLabelUI(false));

        setLayout(new java.awt.BorderLayout());

        mainUIPanel.setLayout(new java.awt.BorderLayout());

        addButton.setText("Add New");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(quitButton)
                .addContainerGap())
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, quitButton});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton)
                    .addComponent(addButton))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        mainUIPanel.add(buttonPanel, java.awt.BorderLayout.PAGE_END);
        mainUIPanel.add(quadrantPanel1, java.awt.BorderLayout.CENTER);

        xLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel.setText("Urgency");
        mainUIPanel.add(xLabel, java.awt.BorderLayout.PAGE_START);

        yLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yLabel.setText("Importance");
        mainUIPanel.add(yLabel, java.awt.BorderLayout.LINE_START);

        add(mainUIPanel, java.awt.BorderLayout.CENTER);
        jXLayer = new JXLayer<JComponent>(mainUIPanel,lockableUI);

        add(jXLayer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        lockableUI.setLocked(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel mainUIPanel;
    private org.jchronos.ui.QuadrantPanel quadrantPanel1;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel yLabel;
    // End of variables declaration//GEN-END:variables
    public static class TodoLockableUI extends LockableUI {

        private TodoPanel todoPanel = new TodoPanel();

        public TodoLockableUI(LayerEffect... lockedEffects) {
            super(lockedEffects);
            todoPanel.setVisible(false);
            todoPanel.setCancelAction(new ActionListener() {
                public void actionPerformed(ActionEvent event) {
                    setLocked(false);
                }
            });
        }

        public TodoPanel getTodoPanel() {
            return todoPanel;
        }

        @Override
        @SuppressWarnings("unchecked")
        public void installUI(JComponent c) {
            super.installUI(c);
            JXLayer l = (JXLayer) c;
            l.getGlassPane().setLayout(new GridBagLayout());
            l.getGlassPane().add(todoPanel);
            todoPanel.setCursor(Cursor.getDefaultCursor());
        }

        @Override
        @SuppressWarnings("unchecked")
        public void uninstallUI(JComponent c) {
            super.uninstallUI(c);
            JXLayer l = (JXLayer) c;
            l.getGlassPane().setLayout(new FlowLayout());
            l.getGlassPane().remove(todoPanel);
        }

        @Override
        public void setLocked(boolean isLocked) {
            super.setLocked(isLocked);
            todoPanel.setVisible(isLocked);
        }
    }
}
